CREATE TABLE [EA].[L_CLIENT_REQUESTING_OFFICE] (
    [CLIENT_REQUESTING_OFFICE_ID] INT           IDENTITY (1, 1) NOT NULL,
    [CLIENT_ID]                   INT           NOT NULL,
    [REQUESTING_OFFICE_ID]        INT           NULL,
    [IS_DELETED]                  BIT           NULL,
    [CREATE_DATE]                 DATETIME      NULL,
    [CREATE_LOGIN_ID]             VARCHAR (255) NULL,
    [UPDATE_DATE]                 DATETIME      NULL,
    [UPDATE_LOGIN_ID]             VARCHAR (255) NULL,
    CONSTRAINT [PK_L_CLIENT_REQUESTING_OFFICE] PRIMARY KEY CLUSTERED ([CLIENT_REQUESTING_OFFICE_ID] ASC),
    CONSTRAINT [FK_L_CLIENT_REQUESTING_OFFICE_L_CLIENT] FOREIGN KEY ([CLIENT_ID]) REFERENCES [EA].[L_CLIENT] ([CLIENT_ID]),
    CONSTRAINT [FK_L_CLIENT_REQUESTING_OFFICE_L_REQUESTING_OFFICE] FOREIGN KEY ([CLIENT_REQUESTING_OFFICE_ID]) REFERENCES [EA].[L_REQUESTING_OFFICE] ([REQUESTING_OFFICE_ID])
);

