CREATE TABLE [EA].[L_MASTER_TYPE] (
    [MASTER_TYPE_ID]  INT           IDENTITY (1, 1) NOT NULL,
    [REF_CODE]        VARCHAR (255) NULL,
    [DESCRIPTION]     VARCHAR (255) NULL,
    [IS_DELETED]      BIT           NULL,
    [CREATE_DATE]     DATETIME      NULL,
    [CREATE_LOGIN_ID] VARCHAR (255) NULL,
    [UPDATE_DATE]     DATETIME      NULL,
    [UPDATE_USER_ID]  VARCHAR (255) NULL,
    CONSTRAINT [PK_L_MASTER_TYPE] PRIMARY KEY CLUSTERED ([MASTER_TYPE_ID] ASC)
);

