CREATE TABLE [EA].[L_REQUESTING_REGION] (
    [REQUESTING_REGION_ID]   INT           IDENTITY (1, 1) NOT NULL,
    [REQUESTING_REGION_NAME] VARCHAR (255) NULL,
    [IS_DELETED]             BIT           NULL,
    [CREATE_DATE]            DATETIME      NULL,
    [CREATE_LOGIN_ID]        VARCHAR (255) NULL,
    [UPDATE_DATE]            DATETIME      NULL,
    [UPDATE_LOGIN_ID]        VARCHAR (255) NULL,
    CONSTRAINT [PK_L_REQUESTING_REGION] PRIMARY KEY CLUSTERED ([REQUESTING_REGION_ID] ASC)
);

