CREATE TABLE [EA].[L_SUB_SERVICES] (
    [SUB_SERVICES_ID]   INT           IDENTITY (1, 1) NOT NULL,
    [SERVICES_ID]       INT           NULL,
    [SUB_SERVICES_NAME] VARCHAR (MAX) NULL,
    [IS_DELETED]        BIT           NULL,
    [CREATE_DATE]       DATETIME      NULL,
    [CREATE_LOGIN_ID]   VARCHAR (255) NULL,
    [UPDATE_DATE]       DATETIME      NULL,
    [UPDATE_LOGIN_ID]   VARCHAR (255) NULL,
    CONSTRAINT [PK_L_SUB_SERVICES] PRIMARY KEY CLUSTERED ([SUB_SERVICES_ID] ASC),
    CONSTRAINT [FK_L_SUB_SERVICES_L_SERVICES] FOREIGN KEY ([SERVICES_ID]) REFERENCES [EA].[L_SERVICES] ([SERVICES_ID])
);

