CREATE TABLE [EA].[L_USR_STATUS] (
    [USR_STATUS_ID]   INT           IDENTITY (1, 1) NOT NULL,
    [USR_STATUS_NAME] VARCHAR (255) NULL,
    [IS_DELETED]      BIT           NULL,
    [CREATE_DATE]     DATETIME      NULL,
    [CREATE_LOGIN_ID] VARCHAR (255) NULL,
    [UPDATE_DATE]     DATETIME      NULL,
    [UPDATE_LOGIN_ID] VARCHAR (255) NULL,
    CONSTRAINT [PK_L_USR_STATUS] PRIMARY KEY CLUSTERED ([USR_STATUS_ID] ASC)
);

