CREATE TABLE [EA].[T_USR_ALERT_RECIPENT] (
    [USR_ALERT_RECIPENT_ID] INT            IDENTITY (1, 1) NOT NULL,
    [USR_ID]                INT            NULL,
    [RECIPIENT_NAME]        VARCHAR (255)  NULL,
    [RECIPIENT_EMAIL_ID]    VARCHAR (255)  NULL,
    [RECIPIENT_MOBILE]      NVARCHAR (255) NULL,
    [IS_DELETED]            BIT            NULL,
    [CREATE_DATE]           DATETIME       NULL,
    [CREATE_LOGIN_ID]       VARCHAR (255)  NULL,
    [UPDATE_DATE]           DATETIME       NULL,
    [UPDATE_LOGIN_ID]       VARCHAR (255)  NULL,
    [COUNTRY_CODE]          VARCHAR (255)  NULL,
    [IS_NOTIFY]             BIT            NULL,
    CONSTRAINT [PK_T_USR_ALERT_RECIPENT] PRIMARY KEY CLUSTERED ([USR_ALERT_RECIPENT_ID] ASC),
    CONSTRAINT [FK_T_USR_ALERT_RECIPENT_T_USR] FOREIGN KEY ([USR_ID]) REFERENCES [EA].[T_USR] ([USR_ID])
);

