CREATE TABLE [EA].[T_USR_HIST] (
    [USR_HIST_ID]              INT            IDENTITY (1, 1) NOT NULL,
    [USR_ID]                   INT            NULL,
    [USR_CODE]                 VARCHAR (255)  NULL,
    [REQUEST_OFFICE_ID]        INT            NULL,
    [CLIENT_ID]                INT            NULL,
    [CLIENT_LOGIN_ID]          VARCHAR (255)  NULL,
    [SERVICE_DESCRIPTION]      NVARCHAR (MAX) NULL,
    [USR_START_DATE]           DATETIME       NULL,
    [USR_END_DATE]             DATETIME       NULL,
    [OM_LOGIN_ID]              VARCHAR (255)  NULL,
    [AUTHOR_ID]                VARCHAR (255)  NULL,
    [AUTHOR_START_DATE]        DATETIME       NULL,
    [AUTHOR_END_DATE]          DATETIME       NULL,
    [AUTHOR_COMMENT]           VARCHAR (MAX)  NULL,
    [REVIEWER_ID]              VARCHAR (255)  NULL,
    [REVIEWER_START_DATE]      DATETIME       NULL,
    [REVIEWER_END_DATE]        DATETIME       NULL,
    [REVIEWER_COMMENT]         VARCHAR (MAX)  NULL,
    [INCLUDE_KEYWORDS]         NVARCHAR (MAX) NULL,
    [EXCLUDE_KEYWORDS]         NVARCHAR (MAX) NULL,
    [USR_STATUS_ID]            INT            NULL,
    [SERVICE_TYPE_CATEGORY_ID] INT            NULL,
    [DIRECTOR_ID]              VARCHAR (255)  NULL,
    [IS_DELETED]               BIT            NULL,
    [CREATE_DATE]              DATETIME       NULL,
    [CREATE_LOGIN_ID]          VARCHAR (255)  NULL,
    [UPDATE_DATE]              DATETIME       NULL,
    [UPDATE_LOGIN_ID]          VARCHAR (255)  NULL,
    CONSTRAINT [PK_T_USR_HIST] PRIMARY KEY CLUSTERED ([USR_HIST_ID] ASC)
);

