CREATE TABLE [EA].[L_MASTER_VALUE] (
    [MASTER_VALUE_ID] INT           IDENTITY (1, 1) NOT NULL,
    [MASTER_TYPE_ID]  INT           NULL,
    [REF_CODE]        VARCHAR (255) NULL,
    [DESCRIPTION]     VARCHAR (MAX) NULL,
    [IS_DELETED]      BIT           NULL,
    [CREATE_DATE]     DATETIME      NULL,
    [CREATE_LOGIN_ID] VARCHAR (255) NULL,
    [UPDATE_DATE]     DATETIME      NULL,
    [UPDATE_USER_ID]  VARCHAR (255) NULL,
    CONSTRAINT [PK_L_MASTER_VALUE] PRIMARY KEY CLUSTERED ([MASTER_VALUE_ID] ASC),
    CONSTRAINT [FK_L_MASTER_VALUE_L_MASTER_TYPE] FOREIGN KEY ([MASTER_TYPE_ID]) REFERENCES [EA].[L_MASTER_TYPE] ([MASTER_TYPE_ID])
);

