CREATE TABLE [EA].[L_SERVICE_TYPE] (
    [SERVICE_TYPE_ID]   INT           IDENTITY (1, 1) NOT NULL,
    [SERVICE_TYPE_NAME] VARCHAR (MAX) NULL,
    [IS_DELETED]        BIT           NULL,
    [CREATE_DATE]       DATETIME      NULL,
    [CREATE_LOGIN_ID]   VARCHAR (255) NULL,
    [UPDATE_DATE]       DATETIME      NULL,
    [UPDATE_LOGIN_ID]   VARCHAR (255) NULL,
    CONSTRAINT [PK_L_SERVICE_TYPE] PRIMARY KEY CLUSTERED ([SERVICE_TYPE_ID] ASC)
);

