CREATE TABLE [EA].[L_REQUESTING_OFFICE] (
    [REQUESTING_OFFICE_ID]   INT           IDENTITY (1, 1) NOT NULL,
    [REGION_ID]              INT           NOT NULL,
    [REQUESTING_OFFICE_NAME] VARCHAR (255) NULL,
    [IS_DELETED]             BIT           NULL,
    [CREATE_DATE]            DATETIME      NULL,
    [CREATE_LOGIN_ID]        VARCHAR (255) NULL,
    [UPDATE_DATE]            DATETIME      NULL,
    [UPDATE_LOGIN_ID]        VARCHAR (255) NULL,
    CONSTRAINT [PK_L_REQUESTING_OFFICE] PRIMARY KEY CLUSTERED ([REQUESTING_OFFICE_ID] ASC),
    CONSTRAINT [FK_L_REQUESTING_OFFICE_L_REQUESTING_REGION] FOREIGN KEY ([REGION_ID]) REFERENCES [EA].[L_REQUESTING_REGION] ([REQUESTING_REGION_ID])
);

