CREATE TABLE [EA].[T_USR_RECIPIENTS] (
    [USR_RECIPIENTS_ID]      INT           IDENTITY (1, 1) NOT NULL,
    [USR_ID]                 INT           NULL,
    [RECIPIENT_NAME]         VARCHAR (255) NULL,
    [IS_DELETED]             BIT           NULL,
    [CREATE_DATE]            DATETIME      NULL,
    [CREATE_LOGIN_ID]        VARCHAR (255) NULL,
    [UPDATE_DATE]            DATETIME      NULL,
    [UPDATE_LOGIN_ID]        VARCHAR (255) NULL,
    [RECIPIENT_COUNTRY_CODE] VARCHAR (255) NULL,
    CONSTRAINT [PK_T_USR_RECIPIENTS] PRIMARY KEY CLUSTERED ([USR_RECIPIENTS_ID] ASC),
    CONSTRAINT [FK_T_USR_RECIPIENTS_T_USR] FOREIGN KEY ([USR_ID]) REFERENCES [EA].[T_USR] ([USR_ID])
);

