CREATE TABLE [EA].[T_USR_OPERATION_MANAGER] (
    [USR_OM_ID]       INT           IDENTITY (1, 1) NOT NULL,
    [USR_ID]          INT           NULL,
    [USR_RECIPENT_ID] INT           NULL,
    [OM_NAME]         VARCHAR (255) NULL,
    [START_DATE]      DATETIME      NULL,
    [END_DATE]        DATETIME      NULL,
    [DESCRIPTION]     VARCHAR (MAX) NULL,
    [IS_DELETED]      BIT           NULL,
    [CREATE_DATE]     DATETIME      NULL,
    [CREATE_LOGIN_ID] VARCHAR (255) NULL,
    [UPDATE_DATE]     DATETIME      NULL,
    [UPDATE_LOGIN_ID] VARCHAR (255) NULL,
    CONSTRAINT [PK_T_USR_OPERATION_MANAGER] PRIMARY KEY CLUSTERED ([USR_OM_ID] ASC),
    CONSTRAINT [FK_T_USR_OPERATION_MANAGER_T_USR] FOREIGN KEY ([USR_ID]) REFERENCES [EA].[T_USR] ([USR_ID]),
    CONSTRAINT [FK_T_USR_OPERATION_MANAGER_T_USR_RECIPIENTS] FOREIGN KEY ([USR_RECIPENT_ID]) REFERENCES [EA].[T_USR_RECIPIENTS] ([USR_RECIPIENTS_ID])
);

